# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

def fibonacci(i, j, limit):
    sum = 0

    if j < limit:
        if j % 2 == 0:
            sum += j
        aux = i + j
        i = j
        j = aux
        sum += fibonacci(i, j, limit)
        return sum
    else:
        return sum


print("The sum of all even numbers in the Fibonacci sequence below 40000000 equals", fibonacci(1, 2, 4000000))
